"""Initial migration

Revision ID: 61dc0584afcb
Revises: 
Create Date: 2025-03-13 18:27:56.916394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dc0584afcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basketball_shot_types',
    sa.Column('shot_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shot_type_id')
    )
    op.create_table('schools',
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sport_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stadiums',
    sa.Column('stadium_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('stadium_id')
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('league_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.String(), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.Column('loser_id', sa.String(), nullable=True),
    sa.Column('stadium_id', sa.String(), nullable=True),
    sa.Column('is_neutral_site', sa.Boolean(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('game_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loser_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.stadium_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('current_team_id', sa.String(), nullable=True),
    sa.Column('uniform_number', sa.String(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_pick', sa.Integer(), nullable=True),
    sa.Column('draft_team_id', sa.String(), nullable=True),
    sa.Column('graduation_yr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('basketball_player_stats',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.String(), nullable=False),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('basketball_shots',
    sa.Column('player_shot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('shot_type_id', sa.Integer(), nullable=False),
    sa.Column('assist_id', sa.String(), nullable=True),
    sa.Column('shot_made', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('base_pct', sa.Float(), nullable=False),
    sa.Column('side_pct', sa.Float(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('side_of_basket', sa.String(), nullable=False),
    sa.Column('clutch', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assist_id'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_type_id'], ['basketball_shot_types.shot_type_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('player_shot_id')
    )
    op.create_table('basketball_team_stats',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('pts_in_pt', sa.Integer(), nullable=True),
    sa.Column('possessions', sa.Integer(), sa.Computed('fga + 0.44 * fta - oreb + turnovers', ), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_table('game_lines',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('spread_line', sa.Integer(), nullable=True),
    sa.Column('money_line', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('spread_outcome', sa.Integer(), nullable=False),
    sa.Column('money_outcome', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_table('over_unders',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('over_under', sa.Float(), nullable=False),
    sa.Column('over_line', sa.Integer(), nullable=True),
    sa.Column('under_line', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ou_outcome', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('periods',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id', 'period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periods')
    op.drop_table('over_unders')
    op.drop_table('game_lines')
    op.drop_table('basketball_team_stats')
    op.drop_table('basketball_shots')
    op.drop_table('basketball_player_stats')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('stadiums')
    op.drop_table('sports')
    op.drop_table('schools')
    op.drop_table('basketball_shot_types')
    # ### end Alembic commands ###
