"""Added Column to stat metrics

Revision ID: 7485a250f786
Revises: e8c18df3bb7e
Create Date: 2025-03-26 16:40:04.439840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7485a250f786'
down_revision: Union[str, None] = 'e8c18df3bb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_lines', 'money_outcome',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('stat_metrics', sa.Column('best_value', sa.Numeric(), nullable=True))
    op.add_column('stat_metrics', sa.Column('worst_value', sa.Numeric(), nullable=True))
    op.drop_column('stat_metrics', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_metrics', sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('stat_metrics', 'worst_value')
    op.drop_column('stat_metrics', 'best_value')
    op.alter_column('game_lines', 'money_outcome',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
