"""Fixing migrations

Revision ID: 7eae3020adcb
Revises: 61dc0584afcb
Create Date: 2025-03-23 09:28:53.946803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eae3020adcb'
down_revision: Union[str, None] = '61dc0584afcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_metrics',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'entity_type', 'entity_id', 'timeframe', 'metric_name')
    )
    op.create_table('stat_metrics',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('q1', sa.Numeric(), nullable=True),
    sa.Column('q2', sa.Numeric(), nullable=True),
    sa.Column('q4', sa.Numeric(), nullable=True),
    sa.Column('q6', sa.Numeric(), nullable=True),
    sa.Column('q8', sa.Numeric(), nullable=True),
    sa.Column('q9', sa.Numeric(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'entity_type', 'timeframe', 'metric_name')
    )
    op.alter_column('players', 'current_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'current_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('stat_metrics')
    op.drop_table('game_metrics')
    # ### end Alembic commands ###
