"""create SwingResult table

Revision ID: ab435830cd20
Revises: 2ae1a1a76295
Create Date: 2025-04-27 07:57:35.967141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab435830cd20'
down_revision: Union[str, None] = '2ae1a1a76295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swing_results',
    sa.Column('swing_result_id', sa.Integer(), nullable=False),
    sa.Column('pitch_result_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_result_name'], ['pitch_result_types.pitch_result_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('swing_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swing_results')
    # ### end Alembic commands ###
